name = "psikohekimfrontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
NODE_VERSION = "20.18.0"

# Base URLs (auth = Keycloak, api = Backend)
VITE_KEYCLOAK_BASE_URL = "https://auth.iyihislerapp.com"
VITE_PSIKOHEKIM_BASE_URL = "https://api.iyihislerapp.com"
VITE_BPMN_BASE_URL = "https://bpmn.iyihislerapp.com"

# Keycloak Endpoints (api proxy - CORS i√ßin)
VITE_KEYCLOAK_BASE_URL = "https://api.iyihislerapp.com"
VITE_KEYCLOAK_GET_TOKEN_URL = "https://api.iyihislerapp.com/keycloak/getToken"
VITE_KEYCLOAK_GET_USER_INFO_URL = "https://api.iyihislerapp.com/keycloak/userInfo"
VITE_KEYCLOAK_USERS_URL = "https://api.iyihislerapp.com/api/users"

# Patient Endpoints
VITE_PATIENT_LIST_URL = "https://api.iyihislerapp.com/patient/all"
VITE_PATIENT_DETAILS_URL = "https://api.iyihislerapp.com/patient/details"
VITE_PATIENT_SEARCH_URL = "https://api.iyihislerapp.com/patient/search"
VITE_PATIENT_ADD_URL = "/patient/addPatient"

# Therapist Endpoints
VITE_THERAPIST_LIST_URL = "https://api.iyihislerapp.com/therapist/all"
VITE_THERAPIST_DETAILS_URL = "https://api.iyihislerapp.com/therapist/details"
VITE_THERAPIST_SEARCH_URL = "https://api.iyihislerapp.com/therapist/search"
VITE_THERAPIST_ADD_URL = "https://api.iyihislerapp.com/therapist/addTherapist"

# Therapist-Patient
VITE_THERAPIST_PATIENT_PATIENTS_URL = "https://api.iyihislerapp.com/therapist-patient"
